name: CI

env:
  VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"
  VCPKG_COMMIT_ID: "b2cb0da531c2f1f740045bfe7c4dac59f0b2b69c"

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    name: Build Windows EXE
    runs-on: windows-2022

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable
          targets: x86_64-pc-windows-gnu

      - name: Install prerequisites with vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgGitCommitId: ${{ env.VCPKG_COMMIT_ID }}

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2

      - name: Build Release EXE
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target=x86_64-pc-windows-gnu

      - name: Upload RustDesk .exe
        uses: actions/upload-artifact@v3
        with:
          name: rustdesk-exe
          path: target/x86_64-pc-windows-gnu/release/rustdesk.exe
